### ISSUE TITLE
Deprecated: autowiring services based on the types

### ISSUE THREAD

**Issue by encreinformatique** [michaeldegroot/DoctrineEncryptBundle#11]
Symfony (3.4 in my case) is throwing deprecation warnings.

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "ambta_doctrine_encrypt.encryptor" service to "Ambta\DoctrineEncryptBundle\Encryptors\EncryptorInterface" instead.

**Comment by psmsmets** [comment]
You can create an alias to the service and inject the dependency in an extension of the AbstractController class, which is working in Symfony 4.2.5

In services.yaml add an alias to the existing (deprecated) service:

```
services:
    Ambta\DoctrineEncryptBundle\Encryptors\EncryptorInterface:
        alias: ambta_doctrine_encrypt.encryptor
        public: false
```

And in your controller you can now inject the class (which is an alias to the service):

```
use Ambta\DoctrineEncryptBundle\Encryptors\EncryptorInterface;

class myController extends AbstractController
{

    private $encryptor;
    
    public function __construct(EncryptorInterface $encryptor)
    {
        $this->encryptor = $encryptor;
    }

    public function my_function():
    {
            $this->encryptor->encrypt();
            $this->encryptor->decrypt();
    }

}
```
