### ISSUE TITLE
Travis & Unit testing

### ISSUE THREAD

**Issue by michaeldegroot** [michaeldegroot/DoctrineEncryptBundle#19]
- ~~Add database to travis build~~
 - Create functional tests that interact with database
 - ~~Enable coverage report~~
 - Try to get as high enough coverage as possible
 - Create edge cases testing (items from current issue list for example)

**Comment by michaeldegroot** [comment]
https://github.com/michaeldegroot/DoctrineEncryptBundle/tree/travis

**Comment by michaeldegroot** [comment]
trying to activate travis on the travis branch.. but it's not letting me.. I must be missing something?

![image](https://user-images.githubusercontent.com/1427870/58356253-38c2a880-7e77-11e9-8241-e7fa10287edb.png)


.travis.yml
```
language: php

branches:
  only:
  - gh-pages
  - /.*/

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
      # Minimum supported versions
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"

    - php: 7.3
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

      # Latest commit to master
    - php: 7.3
      env: STABILITY="dev"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

branches:
  only:
    - master
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+\.\d+$/'

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit $PHPUNIT_FLAGS
```
